export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const GET_CURRENT_LOCATION = "GET_CURRENT_LOCATION";

export const SET_CURRENT_LOCATION = "SET_CURRENT_LOCATION";
