export const GET_TOILETS_REQUEST = "GET_TOILETS_REQUEST";
export const GET_TOILETS_SUCCESS = "GET_TOILETS_SUCCESS";
export const GET_TOILETS_FAILURE = "GET_TOILETS_FAILURE";

export const SET_CURRENT_TOILET = "SET_CURRENT_TOILET";
