export const GET_TOILETS_REQUEST = "GET_TOILETS_REQUEST";
export const GET_TOILETS_SUCCESS = "GET_TOILETS_SUCCESS";
export const GET_TOILETS_FAILURE = "GET_TOILETS_FAILURE";

export const SET_CURRENT_TOILET = "SET_CURRENT_TOILET";

export const POST_REVIEW_REQUEST = "POST_REVIEW_REQUEST";
export const POST_REVIEW_SUCCESS = "POST_REVIEW_SUCCESS";
export const POST_REVIEW_FAILURE = "POST_REVIEW_FAILURE";

export const CLEAN_UP_POSTING_SUCCESS = "CLEAN_UP_POSTING_SUCCESS";
